spring:
  application:
    name: DesafioGerenciamentoContasBancarias
  datasource:
    url: jdbc:mysql://localhost:3306/banco_contas_bancarias
    password: "${DATASOURCE_PASSWORD}"
    username: "${DATASOURCE_USERNAME}"
    Driver-class-name: com.mysql.cj.jdbc.Driver
